name: Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run Black
      run: |
        black --check --line-length 79 src/ tests/

    - name: Run Flake8
      run: |
        flake8 --max-line-length 79 --extend-ignore=E203 src/ tests/

    - name: Run isort
      run: |
        isort --check-only --profile black --line-length 79 src/ tests/

    - name: Run mypy
      run: |
        mypy src/
      continue-on-error: true
